INFO:Controller:Launching controller c1: java -server -Xmx512m -Xms512m -Xmn128m -XX:+UseParallelGC -XX:+AggressiveOpts -XX:+UseFastAccessorMethods -XX:MaxInlineSize=8192 -XX:FreqInlineSize=8192 -XX:CompileThreshold=1500 -XX:PreBlockSpin=8 -Dpython.security.respectJavaAccessibility=false -Dlogback.configurationFile=logback.xml -jar target/floodlight.jar -cf /home/rcs/Research/UCB/code/sts/experiments/zeta_final_blackbox_2014_05_29_22_27_25/floodlightconfig.properties
INFO:simulation:Launched controller cc1: java -server -Xmx512m -Xms512m -Xmn128m -XX:+UseParallelGC -XX:+AggressiveOpts -XX:+UseFastAccessorMethods -XX:MaxInlineSize=8192 -XX:FreqInlineSize=8192 -XX:CompileThreshold=1500 -XX:PreBlockSpin=8 -Dpython.security.respectJavaAccessibility=false -Dlogback.configurationFile=logback.xml -jar target/floodlight.jar -cf /home/rcs/Research/UCB/code/sts/experiments/zeta_final_blackbox_2014_05_29_22_27_25/floodlightconfig.properties [PID 2272]
INFO:simulation:Creating topology...
[1;33m[c1] OpenJDK 64-Bit Server VM warning: ignoring option PreBlockSpin=8; support was removed in 7.0_40[1;m

[1;36mKilling controller c1[1;m
Terminating child controllers... OK
127.0.0.1 - - [29/May/2014 22:27:25] "POST / HTTP/1.1" 200 -
Traceback (most recent call last):
  File "./simulator.py", line 122, in <module>
    simulation = simulator.simulate()
  File "/home/rcs/Research/UCB/code/sts/sts/control_flow/mcs_finder.py", line 153, in simulate
    bug_found = self.replay(self.dag, "reproducibility")
  File "/home/rcs/Research/UCB/code/sts/sts/control_flow/mcs_finder.py", line 358, in replay
    results_dir)
  File "/home/rcs/Research/UCB/code/sts/sts/util/rpc_forker.py", line 153, in fork
    task_name, *args, **kws)
  File "/home/rcs/Research/UCB/code/sts/sts/util/rpc_forker.py", line 107, in _invoke_child_rpc
    child_return = connect_with_backoff(invoke_child)
  File "/home/rcs/Research/UCB/code/sts/sts/../pox/pox/lib/util.py", line 412, in connect_with_backoff
    return code_block()
  File "/home/rcs/Research/UCB/code/sts/sts/util/rpc_forker.py", line 105, in invoke_child
    (e.faultCode, e.faultString))
sts.util.rpc_forker.ReplayException: An Exception (code 1) occured in the child replay process: <type 'exceptions.AttributeError'>:
Traceback (most recent call last):
  File "/home/rcs/Research/UCB/code/sts/sts/util/rpc_forker.py", line 52, in _dispatch
    return self.server.funcs[method](*params)
  File "/home/rcs/Research/UCB/code/sts/sts/control_flow/mcs_finder.py", line 330, in play_forward
    simulation = replayer.simulate()
  File "/home/rcs/Research/UCB/code/sts/sts/control_flow/replayer.py", line 161, in simulate
    self.simulation = self.simulation_cfg.bootstrap(self.sync_callback)
  File "/home/rcs/Research/UCB/code/sts/sts/simulation_state.py", line 163, in bootstrap
    simulation.set_pass_through()
  File "/home/rcs/Research/UCB/code/sts/sts/simulation_state.py", line 210, in set_pass_through
    self.god_scheduler.set_pass_through()
  File "/home/rcs/Research/UCB/code/sts/sts/god_scheduler.py", line 70, in set_pass_through
    self.addListener(PendingMessage, self._pass_through_receive_handler)
AttributeError: 'GodScheduler' object has no attribute '_pass_through_receive_handler'

